name: Update Notion Log

on:
  schedule:
    # 매일 15:05 UTC (한국 시간 00:05) 실행 #'55 14 * * *'
    #- cron: '5 15 * * *'
    # 매일 한국 시간 10:00 실행 Test
    - cron: '0 1 * * *'



    
  workflow_dispatch: # 수동 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          
      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
        run: python update_readme.py
        
      - name: Commit and Push
        run: |
          # git config --global user.name "GitHub Action"
          # git config --global user.email "action@github.com"
          git config --global user.name "Anna0626"
          git config --global user.email "Anna0626@users.noreply.github.com"
          git add .
          git commit -m "docs: update notion log" || exit 0
          git push
